# Generated by Django 6.0.6 on 2026-07-15 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Готівка при отриманні'), ('card', 'Оплата карткою онлайн'), ('google_pay', 'Google Pay')], default='cash', max_length=20),
        ),
    ]
